@startuml
skinparam componentStyle uml2
skinparam sequenceArrowThickness 2

skinparam interface {
  borderColor orange
}

header [AOS - UPM]: Servicios asíncronos con RabbittMQ

node "Producer <&envelope-closed>" {
  component "Productor\nde mensajes" as producer #5B9BD5
}

node "Consumer <&envelope-open>" {
  component "Consumidor\nde mensajes" as consumer #5B9BD5
}
'note right
'consume los
'mensajes
'bajo demanda
'end note

node "broker RabbittMQ <&cloud>" {
  component cola #efa97a [
    Cola de mensajes
    //(messages_high)//
  ]
  interface Exchange
'  note left
'    high
'  end note

  producer -up-> Exchange: AMQP
  Exchange -right-> cola: binding

  cola .down.> consumer: AMQP
  consumer -up-> cola
}

@enduml
