version: '3'

services:
    apache:
        build:
          context: .
          dockerfile: .docker/apache/Dockerfile
        container_name: aos_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/aos
        depends_on:
          - php

    php:
        build:
          context: .docker/php
          dockerfile: Dockerfile
        container_name: aos_php
        volumes:
          - .:/home/wwwroot/aos
        environment:
          - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@aos_rabbitmq:5672/%2f/messages
        depends_on:
          - rabbitmq
        ports:
          - 9000:9000

    rabbitmq:   # The RabbitMQ container.
        build:
          context: .
          dockerfile: .docker/rabbitmq/Dockerfile
        container_name: aos_rabbitmq
        ports:
          - 15672:15672
        volumes:
          - rabbitmq:/var/lib/rabbitmq:cached

volumes:
    rabbitmq:
