# https://medium.com/@romaricp/the-perfect-kit-starter-for-a-symfony-4-project-with-docker-and-php-7-2-fda447b6bca1

version: '3'

services:
    apache:
        build:
          context: .
          dockerfile: .docker/apache/Dockerfile
        container_name: sf4_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4
        depends_on:
          - php

    php:
        build:
          context: .docker/php
          dockerfile: Dockerfile
        container_name: sf4_php
        volumes:
          - .:/home/wwwroot/sf4
        environment:
          # - maildev_host=sf4_maildev
          - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@sf4_rabbitmq:5672/%2f/messages
          # - MAILER_URL=smtp://sf4_maildev:25
        depends_on:
          # - maildev
          - rabbitmq
        ports:
          - 9000:9000

#    maildev:
#        image: djfarrelly/maildev
#        container_name: sf4_maildev
#        ports:
#          - 8001:80

    rabbitmq:   # The RabbitMQ container.
        build:
          context: .
          dockerfile: .docker/rabbitmq/Dockerfile
        container_name: sf4_rabbitmq
        ports:
          - 15672:15672
        volumes:
          - rabbitmq:/var/lib/rabbitmq:cached

volumes:
    rabbitmq:
