version: '3'

services:
    producer:
        build:
          context: .
          dockerfile: .docker/apache/Dockerfile
        container_name: producer
        ports:
          - "8000:80"
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled:ro
          - ./:/home/wwwroot/aos
        depends_on:
          - php

    consumer:
        build:
            context: .
            dockerfile: .docker/apache/Dockerfile
        container_name: consumer
        ports:
            - "8080:80"
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled:ro
            - ./:/home/wwwroot/aos
        depends_on:
            - php

    php:
        build:
          context: .docker/php
          dockerfile: Dockerfile
        container_name: php_fpm
        user: root
        volumes:
          - ./:/home/wwwroot/aos:rw
        environment:
          - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@broker_rabbitmq:5672/%2f/messages
          - EXCHANGE_NAME=high
          - QUEUE_NAME=messages_high
        depends_on:
          - rabbitmq
        ports:
          - "9000:9000"

    rabbitmq:
        build:
          context: .
          dockerfile: .docker/rabbitmq/Dockerfile
        container_name: broker_rabbitmq
        ports:
          - "15672:15672"
        volumes:
          - rabbitmq:/var/lib/rabbitmq:cached

volumes:
    rabbitmq:
